version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_urlshort
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: urlshort
      POSTGRES_USER: urlshort
      POSTGRES_PASSWORD: urlshort
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: