version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_urlshort
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: urlshort
      MYSQL_USER: urlshort
      MYSQL_PASSWORD: urlshort
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: