spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8080

recaptcha:
  expected-hostname: ${RECAPTCHA_EXPECTED_HOSTNAME}
  secret: ${RECAPTCHA_SECRET}

app:
  base-url: ${APP_BASE_URL}