spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshort
    username: urlshort
    password: urlshort
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8080

recaptcha:
  expected-hostname: localhost
  secret: ${RECAPTCHA_SECRET}

app:
  base-url: http://localhost:8080/