name: Auto Create PR

on:
  workflow_run:
    workflows: ["Validate Coverage"]
    types:
      - completed

jobs:
  create-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Set HEAD_BRANCH from workflow_run
        run: echo "HEAD_BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Create PR using GitHub Script
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const sourceBranch = process.env.HEAD_BRANCH;

            const existingPRs = await github.rest.pulls.list({
              owner,
              repo,
              head: `${owner}:${sourceBranch}`,
              base: 'main',
              state: 'open'
            });

            if (existingPRs.data.length === 0) {
              await github.rest.pulls.create({
                owner,
                repo,
                title: `[CI] Auto PR from ${sourceBranch} to main`,
                head: sourceBranch,
                base: 'main',
                body: '✅ PR criado automaticamente após validação de cobertura pytest ≥ 90%.'
              });
              console.log(`✅ PR criado de ${sourceBranch} para main`);
            } else {
              const pr = existingPRs.data[0];
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number: pr.number,
                body: pr.body + '\n\n♻️ Atualizado automaticamente.'
              });
              console.log(`♻️ PR existente atualizado: #${pr.number}`);
            }