name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: urlshort
          MYSQL_USER: urlshort
          MYSQL_PASSWORD: urlshort
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (test + jacoco)
        run: mvn clean verify

      - name: Get JaCoCo Coverage Percentage
        id: jacoco-coverage
        run: |
          # Extrair a porcentagem de cobertura do arquivo de relatório JaCoCo
          COVERAGE=$(grep -oP 'TOTAL\s+\|\s+\d+\s+\|\s+\d+\s+\|\s+\d+\s+\|\s+\d+\s+\|\s+(\d+)%' target/site/jacoco/index.html | sed 's/.*\s\|\%//g')
          echo "Coverage: $COVERAGE%"
          echo "::set-output name=coverage::$COVERAGE"

      - name: Update Badge
        uses: shields/badge-maker-action@v1
        with:
          label: 'coverage'
          message: ${{ steps.jacoco-coverage.outputs.coverage }}%
          color: brightgreen
