name: Validate Coverage

on:
  push:
    branches-ignore:
      - main

jobs:
  validate-coverage:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: urlshort
          MYSQL_USER: urlshort
          MYSQL_PASSWORD: urlshort
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Wait for MySQL
        run: |
          echo "Esperando MySQL iniciar..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u urlshort -purlshort --silent; then
              echo "MySQL pronto!"
              break
            fi
            echo "Aguardando MySQL ($i)..."
            sleep 2
          done

      - name: Run tests and check coverage
        run: mvn clean verify